services:
  - type: web
    name: boleteria-user-platform
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true